export const routes = {
  MAIN_PAGE: "/",
  PROMO: "/promo",
  PIZZA: "/pizza",
  DRINKS: "/drinks",
  SIDES: "/sides",
  DESSERTS: "/desserts",
  ORDER_PAGE: "/order",
  CLIENT_PAGE: "/client",
  AUTH: "/auth",
  DEVELOPERS: "/devs",
  // ABOUT_DEV_PAGE: "/about-developers",

  ADMIN_PAGE: "/admin",
  ADMIN_ORDER_LISTS: "/admin/order-lists",
  ADMIN_CREATE_PRODUCT: "/admin/create-product",
  ADMIN_UPDATE_PRODUCT: "/admin/update-product",
  ADMIN_UPDATE_PRODUCT_ITEM: "/admin/update-product-item",
  ADMIN_UPDATE_PROMO: "/admin/update-promo",
};
